services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api.dev
    container_name: api
    # ports:
    #   - 3000:3000
    volumes:
      - .:/app
    depends_on:
       db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    # ports:
    #   - 8080:8080

